services:
  - type: web
    name: tixcraft-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip curl xvfb libxi6 libgconf-2-4 default-jdk
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
      unzip /tmp/chromedriver.zip -d /usr/local/bin/
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false